clickhouse:
  replicaCount: 2
  repository: pltvs/clickhouse-server
  tag: latest
  pullPolicy: Always
  writerPass: 2c82mirS
  readerPass: gFzFTUQ9

  lb:
    enabled: false
    restPort: 8123
    rpcPort: 9000

  resources:
    limits:
      cpu: 125m
      memory: 256Mi
    requests:
      cpu: 125m
      memory: 256Mi

  ## Enable persistence using Persistent Volume Claims
  ## ref: http://kubernetes.io/docs/user-guide/persistent-volumes/
  ##
  persistence:
    ## The path the volume will be mounted at
    mountPath: /var/lib/clickhouse

    ## Persistent Volume Storage Class
    ## If defined, storageClassName: <storageClass>
    ## If set to "-", storageClassName: "", which disables dynamic provisioning
    ## If undefined (the default) or set to null, no storageClassName spec is
    ##   set, choosing the default provisioner.  (gp2 on AWS, standard on
    ##   GKE, AWS & OpenStack)
    # storageClass: "ssd"
    accessModes:
      - ReadWriteOnce
    size: 1Gi

  ## Node selector
  ## ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#nodeselector
  nodeSelector: {}

  ## Affinity
  ## ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#affinity-and-anti-affinity
  affinity: {}

  ## Tolerations
  ## ref: https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/
  tolerations: []

# deploys clickhouse-client
client:
  enabled: true

# zookeeper
zookeeper:
  repository: gcr.io/google_samples/k8szk
  tag: v1
  replicaCount: 2

  resources:
    limits:
      cpu: 125m
      memory: 256Mi
    requests:
      cpu: 125m
      memory: 256Mi

  ## Enable persistence using Persistent Volume Claims
  ## ref: http://kubernetes.io/docs/user-guide/persistent-volumes/
  ##
  persistence:
    ## The path the volume will be mounted at
    mountPath: /var/lib/zookeeper

    ## Persistent Volume Storage Class
    ## If defined, storageClassName: <storageClass>
    ## If set to "-", storageClassName: "", which disables dynamic provisioning
    ## If undefined (the default) or set to null, no storageClassName spec is
    ##   set, choosing the default provisioner.  (gp2 on AWS, standard on
    ##   GKE, AWS & OpenStack)
    # storageClass: "ssd"
    accessModes:
      - ReadWriteOnce
    size: 1Gi

  ## Node selector
  ## ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#nodeselector
  nodeSelector: {}

  ## Affinity
  ## ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#affinity-and-anti-affinity
  affinity: {}

  ## Tolerations
  ## ref: https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/
  tolerations: []

# tabix.io web UI
tabix:
  enabled: false
  lb:
    enabled: false
    port: 8088

# monitoring with graphite
graphite:
  enabled: false
  lb:
    enabled: false
    port: 8080
